name: update cf cdn ip

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 18 * * *"   # 设置定时执行，例如每天零点执行
  workflow_dispatch:    # 允许手动执行
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
          
      - name: Update Cloudflare CDN ip
        run: |
          git clone https://github.com/hello-earth/cloudflare-better-ip.git
          mv ./cloudflare-better-ip/cloudflare/*.txt ./
          wget https://raw.githubusercontent.com/vfarid/cf-clean-ips/main/list.txt -O list.txt
          cat ./*.txt > ./all.txt
          grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}' all.txt | sort -u > ip.txt
          wget https://raw.githubusercontent.com/kinshupoon/CloudflareSpeedTest/master/ip4.txt -O ip4.txt
          cat ./ip4.txt >> ip.txt
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ github.actor }}"
          git status
          git rm -r --cached .
          git add .
          git commit -m "Update .gitignore rules"
          git add -f .gitignore
          git commit -m "Add .gitignore file"
          git add "ip.txt"
          git commit -m "Update ip.txt"
          git push origin main
